name: web3dart_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  build: ^2.3.1
  code_builder: ^4.3.0
  web3dart:
    git:
      url: https://github.com/AstroxNetwork/web3dart.git
  built_collection: ^5.1.1
  path: ^1.8.2
  dart_style: ^2.2.4

dependency_overrides:
  async: any

dev_dependencies:
  build_runner: ^2.2.1
  build_config: ^1.1.0
